# Time windows
WINDOW_MINUTES = 15

# Social scoring weights (must sum to 1.0)
SOCIAL_WEIGHT_GROWTH = 0.4
SOCIAL_WEIGHT_SENTIMENT = 0.3
SOCIAL_WEIGHT_ENGAGEMENT = 0.2
SOCIAL_WEIGHT_MOMENTUM = 0.1

# Final score weights (must sum to 1.0)
FINAL_WEIGHT_SOCIAL = 0.70
FINAL_WEIGHT_ONCHAIN = 0.30

# On-chain scoring weights (must sum to 1.0)
ONCHAIN_WEIGHT_WHALE = 0.5
ONCHAIN_WEIGHT_VOLUME = 0.3
ONCHAIN_WEIGHT_HOLDER = 0.2

# Blockchain whale threshold (USD)
WHALE_TX_THRESHOLD_USD = 50000

# Alert thresholds
ALERT_MENTION_SPIKE_RATIO = 3.0
ALERT_SENTIMENT_FLIP_DELTA = 0.5
ALERT_WHALE_SPIKE_RATIO = 2.0
ALERT_VOLUME_SPIKE_RATIO = 2.5

# Influencer detection
INFLUENCER_ENGAGEMENT_MULTIPLIER = 5.0

# Hype cycle thresholds
HYPE_EARLY_MIN_GROWTH = 0.3
HYPE_EARLY_MIN_SENTIMENT = 0.1
HYPE_PEAK_MIN_MENTIONS = 50
HYPE_PEAK_MAX_SENTIMENT_DELTA = 0.1
HYPE_COOLING_MAX_SENTIMENT_MOMENTUM = -0.05
HYPE_DEAD_MAX_MENTIONS = 5
HYPE_DEAD_MAX_SENTIMENT = 0.0

# Confidence thresholds
CONFIDENCE_HIGH_MIN_POSTS = 50
CONFIDENCE_HIGH_MAX_SENTIMENT_VAR = 0.1
CONFIDENCE_HIGH_MIN_ENGAGEMENT = 0.6
CONFIDENCE_MEDIUM_MIN_POSTS = 20
CONFIDENCE_MEDIUM_MAX_SENTIMENT_VAR = 0.25
CONFIDENCE_MEDIUM_MIN_ENGAGEMENT = 0.3

# Coin detection
TOP_N_COINS = 20
MIN_MENTIONS_TO_TRACK = 3

# Engagement normalization ceiling
ENGAGEMENT_NORMALIZATION_CAP = 1000.0
